### ISSUE TITLE
Bug: `No source info found for this element` when using Locator and React dev tool

### ISSUE THREAD

**Issue by trunghieu0207** [infi-pc/locatorjs#98]
### Where the bug happens

- [ ] Browser Extension
- [ ] Library
- [x] Other

### your browser

Chrome/Edge

### Describe the bug

I used the locatorjs with React dev tool extension and then click on the element, and the error display:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/52905437/230824193-1b6f2a72-a6c1-4dd8-a346-fd025c93440d.png">

### To reproduce

My custom project uses the webpack to build React. I not using React app
You can reproduce the bug in the steps below:

1. Config in root file using locatorjs.
Ex: `Index.tsx`
```javascript
import setupLocatorUI from "@locator/runtime";

if (process.env.NODE_ENV === "development") {
  setupLocatorUI();
}
```
2. Install React dev tool
3. Try clicking on the component

### Additional information

# [Reason]
I checked the source and discovered the check condition is in the wrong order in `getElementInfo` function.
```javascript
return reactAdapter.getElementInfo(target) ||  jsxAdapter.getElementInfo(target) || svelteAdapter.getElementInfo(target);
```
- Using `JSX`

The flow will call the `reactAdapter.getElementInfo(target)` and it returns `null` value then flow continues to call `jsxAdapter.getElementInfo(target)` and it returns the correct value

- Using `JSX` and React dev tool

The flow will call the `reactAdapter.getElementInfo(target)` and it **NOT** returns `null` value then flow cannot call to `jsxAdapter.getElementInfo(target)` so the value is incorrect.

# [Fix]

I changed from
```javascript
return reactAdapter.getElementInfo(target) ||  jsxAdapter.getElementInfo(target) || svelteAdapter.getElementInfo(target);
```
to
```javascript
return jsxAdapter.getElementInfo(target) || reactAdapter.getElementInfo(target) || svelteAdapter.getElementInfo(target);
```
and it works normally

@infi-pc 
You can check it and fix it.  My English skill is not good, you can ask me anytime if you find it difficult to understand.
This is a very useful tool and I want to apply it to my product
Thank for you making the tool!

**Comment by zigsong** [comment]
Is this issue resolved?

**Comment by infi-pc** [comment]
yes, should be solved

**Comment by viscous-coder** [comment]
still not worked
![Screenshot (4)](https://github.com/infi-pc/locatorjs/assets/162081167/bd02bd10-0c25-46fe-a949-c4904163655e)

**Comment by zhanglkx** [comment]
<img width="531" alt="image" src="https://github.com/infi-pc/locatorjs/assets/33960940/b93c3fb2-72cd-4b06-bbf0-f36fc3c20b79">
still has this problem,i use webpack
